# Generated by CodiumAI
import argparse
import pytest
from unittest.mock import patch
from pixi_rocker.pixi import PixiExtension


class TestPixiExtension:

    # Instantiating PixiExtension and verifying the name attribute is set correctly
    def test_name_attribute_initialization(self):
        extension = PixiExtension()
        assert extension.name == "pixi"

    def test_register_arguments(self):
        parser = argparse.ArgumentParser()
        PixiExtension.register_arguments(parser)
        args = parser.parse_args([])
        assert "pixi" in vars(args)

    # Handling missing template files in get_snippet method
    def test_get_snippet_missing_template(self):

        extension = PixiExtension()
        with patch("pkgutil.get_data", return_value=None):
            with pytest.raises(AttributeError):
                extension.get_snippet({})

    # Retrieving the default snippet using get_snippet method
    def test_retrieve_default_snippet(self):

        extension = PixiExtension()
        snippet = extension.get_snippet(None)

        assert snippet is not None

    # Retrieving the user-specific snippet using get_user_snippet method
    def test_retrieve_user_specific_snippet(self):

        extension = PixiExtension()
        snippet = extension.get_user_snippet(None)

        assert snippet is not None
